apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce-inventory
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  DATABASE_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  JWT_SECRET: c3VwZXJzZWNyZXRqd3RrZXk=      # supersecretjwtkey
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==      # redispassword
  S3_ACCESS_KEY: YWNjZXNza2V5MTIz          # accesskey123
  S3_SECRET_KEY: c2VjcmV0a2V5MTIz          # secretkey123
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: ecommerce-inventory
type: kubernetes.io/tls
data:
  # Replace with actual TLS certificate and key
  tls.crt: LS0tLS1CRUdJTi...
  tls.key: LS0tLS1CRUdJTi...