name: Automated Dependency Updates

on:
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 6 AM UTC
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Check for updates
        run: |
          echo "Checking for dependency updates..."
          ncu --format group > dependency-updates.txt
          cat dependency-updates.txt

      - name: Update patch and minor versions
        run: |
          # Update patch versions (safe updates)
          ncu -u --target patch
          
          # Update minor versions for dev dependencies
          ncu -u --target minor --dep dev
          
          # Update specific packages to latest if they're known to be safe
          ncu -u --filter "@types/*,eslint*,prettier*,jest*,@testing-library/*"

      - name: Install updated dependencies
        run: npm install

      - name: Run tests to verify updates
        run: |
          npm run lint
          npm run type-check
          npm run test:packages
        continue-on-error: true

      - name: Check for security vulnerabilities
        run: |
          npm audit --audit-level moderate
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated dependency updates generated by the dependency update workflow.
            
            ### Changes
            - Updated patch versions for all dependencies
            - Updated minor versions for dev dependencies
            - Updated type definitions and tooling packages
            
            ### Verification
            - [x] Linting passes
            - [x] Type checking passes
            - [x] Package tests pass
            - [x] Security audit completed
            
            ### Review Notes
            Please review the changes and run additional tests if needed before merging.
            
            **Generated by:** Automated Dependency Update Workflow
            **Date:** $(date)
          branch: automated-dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
            chore

  update-major-versions:
    name: Check Major Version Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Check for major updates
        run: |
          echo "Checking for major version updates..."
          ncu --target major --format group > major-updates.txt
          cat major-updates.txt

      - name: Create issue for major updates
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            let majorUpdates = '';
            
            try {
              majorUpdates = fs.readFileSync('major-updates.txt', 'utf8');
            } catch (error) {
              console.log('No major updates file found');
              return;
            }
            
            if (majorUpdates.includes('All dependencies match the target')) {
              console.log('No major updates available');
              return;
            }
            
            const issueBody = `## Major Dependency Updates Available
            
            The following major version updates are available and require manual review:
            
            \`\`\`
            ${majorUpdates}
            \`\`\`
            
            ### Action Required
            These updates may contain breaking changes and should be reviewed manually:
            
            1. Review the changelog for each package
            2. Test the updates in a separate branch
            3. Update code if necessary to handle breaking changes
            4. Run full test suite including integration tests
            
            ### Automation
            This issue was created automatically by the dependency update workflow.
            `;
            
            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'dependencies,major-updates',
              state: 'open'
            });
            
            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Major dependency updates available',
                body: issueBody,
                labels: ['dependencies', 'major-updates', 'manual-review']
              });
            } else {
              console.log('Major updates issue already exists');
            }

  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Check for security vulnerabilities
        run: |
          npm audit --audit-level moderate --json > audit-results.json || true
          npm audit --audit-level moderate

      - name: Fix security vulnerabilities
        run: |
          npm audit fix --audit-level moderate
          
          # If there are still vulnerabilities, try force fix for high/critical
          if npm audit --audit-level high; then
            echo "No high/critical vulnerabilities found"
          else
            echo "Attempting to fix high/critical vulnerabilities"
            npm audit fix --force --audit-level high || true
          fi

      - name: Verify fixes
        run: |
          npm install
          npm run lint || true
          npm run type-check || true
          npm run test:packages || true

      - name: Create Security Fix PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'security: fix dependency vulnerabilities'
          title: 'security: automated security vulnerability fixes'
          body: |
            ## Security Vulnerability Fixes
            
            This PR contains automated fixes for security vulnerabilities found in dependencies.
            
            ### Changes
            - Applied `npm audit fix` to resolve security issues
            - Updated vulnerable packages to secure versions
            
            ### Verification Required
            - [ ] All tests pass
            - [ ] Application functionality verified
            - [ ] No breaking changes introduced
            
            ### Security Impact
            This PR addresses security vulnerabilities. Please review and merge promptly after verification.
            
            **Generated by:** Automated Security Update Workflow
            **Date:** $(date)
          branch: security-fixes
          delete-branch: true
          labels: |
            security
            automated
            high-priority

      - name: Notify on critical security issues
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: '🚨 Critical security vulnerabilities detected that could not be automatically fixed!'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}

  docker-base-image-updates:
    name: Check Docker Base Image Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for base image updates
        run: |
          echo "Checking Docker base image updates..."
          
          # Check Node.js base images
          docker pull node:18-alpine
          docker pull node:18-slim
          
          # Get current image digests from Dockerfiles
          grep -r "FROM node:" apps/*/Dockerfile > current-images.txt || true
          
          echo "Current base images:"
          cat current-images.txt || echo "No Dockerfiles found"

      - name: Create issue for base image updates
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = `## Docker Base Image Update Check
            
            This is a periodic check for Docker base image updates.
            
            ### Current Base Images
            Check the current base images used in Dockerfiles and consider updating to:
            - Latest security patches
            - Newer Node.js versions if compatible
            - Optimized image variants
            
            ### Action Items
            1. Review current Dockerfiles
            2. Check for security updates in base images
            3. Test with updated base images
            4. Update if beneficial and compatible
            
            ### Automation
            This issue was created automatically by the dependency update workflow.
            `;
            
            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'docker,base-images',
              state: 'open'
            });
            
            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Docker base image update check',
                body: issueBody,
                labels: ['docker', 'base-images', 'maintenance']
              });
            }